config/routes.rb
Rails.application.routes.draw do

  get 'association_invit_restaurants/new'
  get 'users/show'
  get 'homepage/index'
  root to: 'homepage#index'

  get 'my_profile', to: 'users#show'
  get 'restaurants/best_score', to: 'restaurants#best_score'
  get 'restaurants/discover', to: 'restaurants#discover'
  get 'restaurants/selections', to: 'restaurants#selections'
  get 'restaurants/food_tag/:id', to: 'restaurants#food_tag'
  get 'restaurants/:id/flag', to: 'restaurants#flag'
  get 'restaurants/:id/removeflag', to: 'restaurants#removeflag'
  get 'groups/:id/quit_group', to: 'groups#quit_group', as: 'quit_group'

  delete 'invitations/:id', to: 'invitations#destroy', as: 'invitation_destroy'

  resources :restaurants, only: %i[index show update edit]
  resources :food_tags, only: %i[show update]
  resources :groups, only: %i[new update]
  resources :invitations, only: %i[new show update]
  resources :association_user_invits, only: [:update]
  resources :association_invit_restaurants, only: [:new]

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @selection_rest = Restaurant.all.take(4)
    @best_rest = Restaurant.where.not(score: nil).order(score: :desc).take(4)
    @discover_rest = Restaurant.where(score: nil).take(4)
    @food_tags = FoodTag.all
  end
end

app/views/homepage/_food_tags.html.erb
<div class="container-xxl">
  <a class="anchor" id="categories"></a>
  <div class="row row-cols-3 row-cols-md-6 row-cols-lg-6 g-4">
    <% food_tags.each do |food_tag| %>
      <div class="col">
        <h3 class="mt-3 text-center"><%= food_tag.name %></h3>
        <div class="card">
          <a href="/restaurants/food_tag/<%= food_tag.id %>">
          <% if food_tag.photo.representable? %>
            <%#= link_to image_tag(restaurants_food_tag_path), food_tag.photo.representation(resize_to_limit: [500, 500]), class: "card-img" %>
            <%= image_tag(food_tag.photo.representation(resize_to_limit: [500, 500]), class: "card-img-top card-foodtag") %>
          <% end %>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/homepage/index.html.erb
<%= render 'layouts/navbar', actual_page: 1, notif: true %>

<%= render 'homepage/food_tags', food_tags: @food_tags %>
<%= render 'restaurants/best_score', restaurants: @best_rest, from_home: true %>
<%= render 'restaurants/selections', restaurants: @selection_rest, from_home: true %>
<%= render 'restaurants/discover', restaurants: @discover_rest,from_home: true %>

<%= javascript_pack_tag 'restaurant_index.js' %>