config/routes.rb
Rails.application.routes.draw do

  get 'association_invit_restaurants/new'
  get 'users/show'
  get 'homepage/index'
  root to: 'homepage#index'

  get 'my_profile', to: 'users#show'
  get 'restaurants/best_score', to: 'restaurants#best_score'
  get 'restaurants/discover', to: 'restaurants#discover'
  get 'restaurants/selections', to: 'restaurants#selections'
  get 'restaurants/food_tag/:id', to: 'restaurants#food_tag'
  get 'restaurants/:id/flag', to: 'restaurants#flag'
  get 'restaurants/:id/removeflag', to: 'restaurants#removeflag'
  get 'groups/:id/quit_group', to: 'groups#quit_group', as: 'quit_group'

  delete 'invitations/:id', to: 'invitations#destroy', as: 'invitation_destroy'

  resources :restaurants, only: %i[index show update edit]
  resources :food_tags, only: %i[show update]
  resources :groups, only: %i[new update]
  resources :invitations, only: %i[new show update]
  resources :association_user_invits, only: [:update]
  resources :association_invit_restaurants, only: [:new]

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :association_user_restaurants
  has_many :restaurants, :through => :association_user_restaurants

  has_many :association_user_groups
  has_many :groups, :through => :association_user_groups

  has_many :association_user_invits
  has_many :invitations, :through => :association_user_invits

  validates :nickname, presence: true, uniqueness: true, length: { in: 2..16 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in!
  def show
    @invitations = Invitation.joins(:association_user_invits).where(association_user_invits: { user_id: Current.user.id })
    @groups = Group.joins(:association_user_groups).where(association_user_groups: { user_id: Current.user.id })
    flash[:notice] = 'Vous n\'avez pas de groupe, vous devriez commencer par en créer un.' if @groups.blank?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def vote_result vote
    vote.to_s(2)
  end

  def generator_radio_vote_structure(vote, index, form)
    content = '<div class="col-auto form-check">'
    content += generate_radio_input(vote, index, '1', form)
    content += '<i class="form-check-label vote-box-label text-success bi bi-check2-circle"></i>'
    content += '</div>'
    content += '<div class="col-auto form-check ml-35">'
    content += generate_radio_input(vote, index, '0', form)
    content += '<i class="form-check-label vote-box-label fs-custom-1 text-danger bi bi-x-circle ml-5"></i>'
    content += '</div>'
    content.html_safe
  end

  private

  def generate_radio_input(vote, index, value, form)
    if !vote.nil? && vote_check(vote, index, value)
      form.radio_button :vote, value, class: 'form-check-input vote-box', checked: 'checked', name: 'association_user_invit[vote]['+index.to_s+']'
    else
      form.radio_button :vote, value, class: 'form-check-input vote-box', name: 'association_user_invit[vote]['+index.to_s+']'
    end
  end

  # Conversion du vote(Integer) en Base 2(String), on passe la Base 2 à 3 bits de longueurs pour récupérer les 0 omis par to_s(2)
  # Exemple : 3.to_s(2) => "11", on perd dans ce cas un Bit d'info si jamais on avait 3 restaurants dans l'invitation
  #
  # Le reverse est dû à la pondération des bits qui se fait dans le sens opposé de la lecture d'un string (si on devait le lire char by char)
  # Inverser coté serv aurait été plus simple, une autre méthode d'enregistrement de vote aussi d'ailleurs :)
  # Garder une reférence du restaurant sur chaque vote aurait plus de sens (on va dire que c'est de l'opti espace de stockage :D )
  def vote_check(vote, index, value)
    if vote.to_s(2).length < 2
      (vote.to_s(2).reverse << '00')[index] == value
    elsif vote.to_s(2).length < 3
      (vote.to_s(2).reverse << '0')[index] == value
    else
      vote.to_s(2).reverse[index] == value
    end
  end
end

app/views/users/show.html.erb
<%= render 'layouts/navbar', actual_page: nil, notif: false %>

<div class="container-xxl">
  <a class="anchor" id="my-groups"></a>
  <h2 class="mt-3 mb-3 d-inline-block">Mes groupes</h2>
  <% unless @groups.empty? %>
  &nbsp;&nbsp;&nbsp;<%=  button_to "Créer groupe", new_group_path, method: 'get', class: "btn btn-success", form_class: 'mt-3 mb-3 d-inline-block align-bottom'  %>
  <% end %>
  <div class="row row-cols-1 row-cols-md-4 row-cols-lg-4 g-4">
    <% if !@groups.empty? %>
      <% @groups.each do |group| %>
        <div class="col">
          <div class="btn-group mb-2">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-outline-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <%= group.name %>
              </button>
              <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <% group.users.each do |user| %>
                <li><p class="mb-0 dropdown-item"><%= user.nickname %></p></li>
                <% end %>
              </ul>
            </div>
            <%= link_to quit_group_path(id: group.id), class: "btn btn-outline-info", role: "button" do %>
              <i class="bi bi-door-open text-dark text-decoration-none"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="col">
        <%= button_to "Créer groupe", new_group_path, method: 'get', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

<div class="container-xxl">
  <a class="anchor" id="my-invitations"></a>
  <h2 class="mt-3 mb-3 d-inline-block">Mes invitations</h2>
  <% unless @groups.empty? %>
  &nbsp;&nbsp;&nbsp;<%=  button_to "Créer invitation", new_invitation_path, method: 'get', class: "btn btn-success", form_class: 'mt-3 mb-3 d-inline-block align-bottom'  %>
  <% end %>
  <%# if defined?(from_home) %>   <%#= link_to("(Tout voir ...)", restaurants_best_score_path, method: 'get', class: 'homepage-link d-inline-block') %><%#end %>
  <div class="row row-cols-1 g-4">
    <% if !@invitations.empty? %>
      <% @invitations.each do |invitation| %>
        <div class="col">
          <div class="bg-light card h-100">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <h3 class="card-title"><%= invitation.name %></h3>
                <%= button_to "Supprimer", invitation_destroy_path(id: invitation.id), class: 'btn btn-danger', method: 'delete' %>
              </div>
              <div class="row row-cols-1 row-cols-md-4 g-4">
                <%= render 'restaurants/cards_invit', restaurants: invitation.restaurants %>
                <div class="col d-flex">
                  <h4 class="w-100 text-center align-self-end"><%= invitation.group.name %></h4>
                </div>
              </div>
              <% invitation.association_user_invits.each_with_index do |user_invit, index_loop| %>
                <% if Current.user == user_invit.user %>
                  <%= form_with model: user_invit, local: false, method: 'PATCH' do |form| %>
                    <div class="row row-cols-1 row-cols-md-4 g-4">
                      <% invitation.restaurants.length.times do |index| %>
                        <div class="<% if index_loop.even? %>bg-white<% end %> col">
                          <fieldset id="association_user_invit[vote]['+<%= index.to_s %>+']'">
                            <div class="row row-cols-2 justify-content-center">
                              <%= generator_radio_vote_structure(user_invit.vote, index, form) %>
                            </div>
                          </fieldset>
                        </div>
                      <% end %>
                      <div class="text-center col-auto <% if index_loop.even? %>bg-white<% end %>">
                        <h4><%= user_invit.user.nickname %></h4>
                      </div>
                    </div>
                  <% end %>
                <% else %>
                  <div class="row row-cols-1 row-cols-md-4 g-4">
                    <% invitation.restaurants.length.times do |index| %>
                      <div class="text-center <% if index_loop.even? %>bg-white<% end %> col">
                        <% !user_invit.vote.nil? && if user_invit.vote.to_s(2).reverse[index] == "1" %>
                          <i class="form-check-label vote-box-label text-success bi bi-check2-circle mr-5"></i>
                        <% else %>
                          <i class="form-check-label vote-box-label fs-custom-1 text-danger bi bi-x-circle mr-5"></i>
                        <% end %>
                      </div>
                    <% end %>
                    <div class="text-center col-auto <% if index_loop.even? %>bg-white<% end %>">
                      <h4><%= user_invit.user.nickname %></h4>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="col">
        <p>Vous n'avez aucune invitation pour le moment. Pour créer une invitation commencez par créer un groupe.</p>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_pack_tag 'association_user_invits_update.js' %>