config/routes.rb
Rails.application.routes.draw do

  get 'association_invit_restaurants/new'
  get 'users/show'
  get 'homepage/index'
  root to: 'homepage#index'

  get 'my_profile', to: 'users#show'
  get 'restaurants/best_score', to: 'restaurants#best_score'
  get 'restaurants/discover', to: 'restaurants#discover'
  get 'restaurants/selections', to: 'restaurants#selections'
  get 'restaurants/food_tag/:id', to: 'restaurants#food_tag'
  get 'restaurants/:id/flag', to: 'restaurants#flag'
  get 'restaurants/:id/removeflag', to: 'restaurants#removeflag'
  get 'groups/:id/quit_group', to: 'groups#quit_group', as: 'quit_group'

  delete 'invitations/:id', to: 'invitations#destroy', as: 'invitation_destroy'

  resources :restaurants, only: %i[index show update edit]
  resources :food_tags, only: %i[show update]
  resources :groups, only: %i[new update]
  resources :invitations, only: %i[new show update]
  resources :association_user_invits, only: [:update]
  resources :association_invit_restaurants, only: [:new]

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus
  has_many :dish_categories

  has_many :association_food_tag_restaurants
  has_many :food_tags, :through => :association_food_tag_restaurants

  has_many :association_user_restaurants
  has_many :users, :through => :association_user_restaurants

  has_one_attached :card_photo

  validates :name, presence: true, length: { in: 3..24 }
  validates :description, length: { in: 8..130 }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_user_logged_in!, only: [:flag]
  def index
    @selection_rest = Restaurant.all.take(4)
    @best_rest = Restaurant.where.not(score: nil).order(score: :desc).take(4)
    @discover_rest = Restaurant.where(score: nil).take(4)
    @food_tags = FoodTag.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      redirect_to root_path
    end
  end

  def food_tag
    @restaurants = Restaurant.joins(:association_food_tag_restaurants).where(association_food_tag_restaurants: { food_tag_id: params[:id] })
    @food_tag = FoodTag.find(params[:id])
  end

  def best_score
    @restaurants = Restaurant.where.not(score: nil).order(score: :desc).take(10)
  end

  def discover
    @restaurants = Restaurant.where(score: nil)
  end

  def selections
    @restaurants = Restaurant.all.take(10)
  end

  def flag
    @restaurant = Restaurant.find(params[:id])
    if !@restaurant.blank? &&
       (session[:restaurants_id] ||= []).length < 3 &&
       !session[:restaurants_id].include?(params[:id])
      session[:restaurants_id] << @restaurant.id
      flash[:notice] = 'Restaurant ajouté.'
    else
      flash[:notice] = 'Ajout impossible. Vous avez déjà ajouté 3 restaurants à l\'invitation.'
    end
    redirect_to request.referer
  end

  def removeflag
    @restaurant = Restaurant.find(params[:id])
    if session[:restaurants_id].include?(@restaurant.id)
      session[:restaurants_id] -= [params[:id].to_i]
      flash[:notice] = 'Restaurant retiré de votre invitation.'
    else
      flash[:notice] = 'Retrait impossible. Restaurant non trouvé dans votre invitation.'
    end
    redirect_to request.referer
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :score, :card_photo)
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def convert_score_to_star(score)
    return if score.nil?

    content = ''
    (score.to_f / 2).truncate.times do
      content += '<i class="bi bi-star-fill gold"></i> '
    end
    content += '<i class="bi bi-star-half gold"></i> ' unless score.even?
    ((10.0 - score.to_f) / 2).truncate.times do
      content += '<i class="bi bi-star gold"></i> '
    end
    content.html_safe
  end
end

app/views/restaurants/_best_score.html.erb
<div class="container-xxl">
  <a class="anchor" id="best-score"></a>
  <h2 class="mt-3 mb-3 d-inline-block">Meilleures Notes</h2>
  <% if defined?(from_home) %>   <%= link_to("(Tout voir ...)", restaurants_best_score_path, method: 'get', class: 'homepage-link d-inline-block') %><%end %>
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
    <%= render 'restaurants/cards', restaurants: restaurants %>
  </div>
</div>

app/views/restaurants/_cards.html.erb
<% restaurants.each do |restaurant| %>
  <div class="col">
    <div class="card h-100">
      <a href="/restaurants/<%= restaurant.id %>">
        <% if restaurant.card_photo.representable? %>
          <%= image_tag(restaurant.card_photo.representation(resize_to_limit: [500, 500]), class: "card-img-top card-rest") %>
        <% end %>
      </a>
      <div class="card-body">
        <h5 class="card-title"><%= restaurant.name %></h5>
        <p class="card-text text-truncate"><%= restaurant.description %></p>
        <% unless Current.user.blank? %>
          <% if session[:restaurants_id].nil? || !session[:restaurants_id].include?(restaurant.id) %>
            <%= button_to 'Enregistrer pour inviter', '/restaurants/'+restaurant.id.to_s+'/flag', data: {id: restaurant.id}, method: 'get', class: "btn btn-outline-primary" %>
          <% else %>
            <%= button_to 'Retirer pour l\'invitation', '/restaurants/'+restaurant.id.to_s+'/removeflag', data: {id: restaurant.id}, method: 'get', class: "hidden btn btn-primary" %>
          <% end %>
        <% end %>
        <p class="card-text"><%= convert_score_to_star restaurant.score %> <%= restaurant.score.to_f/2 %> ( <%= restaurant.association_user_restaurants.length %> avis )</p>
        <!-- <a tabindex="0" class="" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="Note de Restaurant" data-bs-content="Ce restaurant n'a pas encore d'avis ou de note. Voulez-vous lui en donner?">( <%#= restaurant.association_user_restaurants.length %> avis )</a>-->
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/_cards_invit.html.erb
<% restaurants.each do |restaurant| %>
  <div class="col">
    <div class="card h-100">
      <a href="/restaurants/<%= restaurant.id %>">
        <% if restaurant.card_photo.representable? %>
          <%= image_tag(restaurant.card_photo.representation(resize_to_limit: [500, 500]), class: "card-img-top card-rest") %>
        <% end %>
      </a>
      <div class="card-body">
        <h5 class="card-title"><%= restaurant.name %></h5>
        <p class="card-text text-truncate"><%= restaurant.description %></p>
        <p class="card-text"><%= convert_score_to_star restaurant.score %> <%= restaurant.score.to_f/2 %> ( <%= restaurant.association_user_restaurants.length %> avis )</p>
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/_discover.html.erb
<div class="container-xxl">
  <a class="anchor" id="discover"></a>
  <h2 class="mt-3 mb-3 d-inline-block">A Découvrir</h2>
  <% if defined?(from_home) %>   <%= link_to("(Tout voir ...)", restaurants_discover_path, method: 'get', class: 'homepage-link d-inline-block') %><%end %>
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
    <%= render 'restaurants/cards', restaurants: restaurants %>
  </div>
</div>

app/views/restaurants/_food_tag.html.erb
<div class="container-xxl">
  <a class="anchor" id="discover"></a>
  <h2 class="mt-3 mb-3 d-inline-block"><%= food_tag.name %></h2>
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
    <%= render 'restaurants/cards', restaurants: restaurants %>
  </div>
</div>

app/views/restaurants/_selections.html.erb
<div class="container-xxl">
  <a class="anchor" id="selections"></a>
  <h2 class="mt-3 mb-3 d-inline-block">Sélection</h2>
  <% if defined?(from_home) %>   <%= link_to("(Tout voir ...)", restaurants_selections_path, method: 'get', class: 'homepage-link d-inline-block') %><%end %>
  <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
    <%= render 'restaurants/cards', restaurants: restaurants %>
  </div>
</div>

app/views/restaurants/best_score.html.erb
<%= render 'layouts/navbar', actual_page: 2, notif: true %>

<%= render 'restaurants/best_score', restaurants: @restaurants %>

<%= javascript_pack_tag 'restaurant_index.js' %>

app/views/restaurants/discover.html.erb
<%= render 'layouts/navbar', actual_page: 3, notif: true %>

<%= render 'restaurants/discover', restaurants: @restaurants %>

<%= javascript_pack_tag 'restaurant_index.js' %>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant do |form| %>
  <%= form.label :score %>
  <%= form.text_field :score %>
  <%= form.label :card_photo %>
  <%= form.file_field :card_photo %>
  <%= form.submit %>
<% end %>

app/views/restaurants/flag.js.erb
$('button[data-id="<%= @restaurant.id %>"').each( function() {
    $(this).toggle();
});

app/views/restaurants/food_tag.html.erb
<%= render 'layouts/navbar', actual_page: nil, notif: true %>

<%= render 'restaurants/food_tag', restaurants: @restaurants, food_tag: @food_tag %>

<%= javascript_pack_tag 'restaurant_index.js' %>

app/views/restaurants/selections.html.erb
<%= render 'layouts/navbar', actual_page: 4, notif: true %>

<%= render 'restaurants/selections',  restaurants: @restaurants %>


<%= javascript_pack_tag 'restaurant_index.js' %>

app/views/restaurants/show.html.erb
<%= render 'layouts/navbar', actual_page: nil %>

<div class="container-xxl">
  <div class="row row-cols-1">
    <div class="col">
      <h2 class="d-inline-block mt-3"><%= @restaurant.name %></h2>
      <p class="d-inline-block">   <%= convert_score_to_star @restaurant.score %> <%= @restaurant.score.to_f/2 %> ( <%= @restaurant.association_user_restaurants.length %> avis )</p>
      <p><%= @restaurant.description %></p>

      <% unless @restaurant.menus.nil? %>
        <h3>Menus</h3>
        <div class="container-fluid">
          <div class="row row-cols-1 row-cols-md-2">
          <% @restaurant.menus.each do |menu| %>
            <div class="px-2 col mt-3">
              <h4 class="d-inline-block"><%= menu.name %> ...</h4> <p class="mb-0 fw-bold float-end d-inline-block"><%= menu.price %> €</p>
              <ul class="list-group">
              <% menu.dishes.each_with_index do |dish, index| %>
                  <li class="list-group-item <% if index.even? %>bg-light<% end %>">
                    <p class="fw-bold d-inline-block"><%= dish.name %></p>
                    <p><%= dish.details %></p>
                  </li>
              <% end %>
              </ul>
            </div>
          <% end %>
          </div>
        </div>
      <% end %>

      <h3 class="pt-3">La carte</h3>
      <div class="container-fluid">
        <% @restaurant.dish_categories.each do |dish_category| %>
          <% unless dish_category.dishes.empty? %>
            <h4 class="pt-3"><%= dish_category.name %></h4>
            <div class="row row-cols-1 row-cols-md-2">
              <ul class="list-group">
                <% dish_category.dishes.each_with_index do |dish, index| %>
                  <li class="list-group-item <% if index.even? %>bg-light<% end %>">
                    <p class="fw-bold d-inline-block"><%= dish.name %></p> <p class="mb-0 fw-bold float-end d-inline-block"><%= dish.price %> €</p>
                    <p><%= dish.details %></p>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>





