config/routes.rb
Rails.application.routes.draw do

  get 'association_invit_restaurants/new'
  get 'users/show'
  get 'homepage/index'
  root to: 'homepage#index'

  get 'my_profile', to: 'users#show'
  get 'restaurants/best_score', to: 'restaurants#best_score'
  get 'restaurants/discover', to: 'restaurants#discover'
  get 'restaurants/selections', to: 'restaurants#selections'
  get 'restaurants/food_tag/:id', to: 'restaurants#food_tag'
  get 'restaurants/:id/flag', to: 'restaurants#flag'
  get 'restaurants/:id/removeflag', to: 'restaurants#removeflag'
  get 'groups/:id/quit_group', to: 'groups#quit_group', as: 'quit_group'

  delete 'invitations/:id', to: 'invitations#destroy', as: 'invitation_destroy'

  resources :restaurants, only: %i[index show update edit]
  resources :food_tags, only: %i[show update]
  resources :groups, only: %i[new update]
  resources :invitations, only: %i[new show update]
  resources :association_user_invits, only: [:update]
  resources :association_invit_restaurants, only: [:new]

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="mt-5 container-fluid bg-dark bg-gradient">
  <div class="text-white container-xxl">
    <div class="row row-cols-1 row-cols-md-2 justify-content-md-center">
      <div class="col mt-3">
        <h5 class="text-center">LetsMIAM</h5>
        <p>Description de l'entreprise en quelques mots</p>
      </div>
      <div class="col col mt-3 col-md-auto">
        <h5 class="text-center">A propos</h5>
        <p class="mb-1">Conditions générales</p>
        <p class="mb-1">Contact</p>
        <p class="mb-1">Mon restau</p>
      </div>
    </div>
    <p class="mb-0 text-center">@ Copyright 2021 : letsmiam.com</p>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top bg-light">
  <div class="container-fluid container-xxl">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link <% if actual_page == 1 %>active<% end %>" <% if actual_page == 1 %>aria-current="page"<% end %> href="<%= url_for(action: 'index', controller: 'homepage') %>">Accueil</a>
        <a class="nav-link <% if actual_page == 2 %>active<% end %>" <% if actual_page == 2 %>aria-current="page"<% end %> href="<%= url_for(action: 'best_score', controller: 'restaurants') %>">Meilleures Notes</a>
        <a class="nav-link <% if actual_page == 3 %>active<% end %>" <% if actual_page == 3 %>aria-current="page"<% end %> href="<%= url_for(action: 'discover', controller: 'restaurants') %>">A Découvrir</a>
        <a class="nav-link <% if actual_page == 4 %>active<% end %>" <% if actual_page == 4 %>aria-current="page"<% end %> href="<%= url_for(action: 'selections', controller: 'restaurants') %>">Sélection</a>
      </div>
    </div>
    <div class="d-flex">
      <% if Current.user %>
        <% if check_invitation_without_vote(Current.user.id) && notif %>
          <i class="notif-envelop bi bi-envelope-exclamation"></i>
        <% end %>
        <%= button_to 'Mes invitations', my_profile_url, method: 'get', class: "btn btn-outline-success mr-5" %>
        <%= button_to 'Se déconnecter', logout_path, method: :delete, class: "btn btn-outline-danger" %>
      <% else %>
        <%= link_to 'S\'enregistrer', sign_up_path, method: 'get', class: "link-dark link-success mr-5 pt-7" %>
        <%= button_to 'Se connecter', sign_in_path, method: 'get', class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</nav>

<div class="container-fluid container-xxl">
  <% flash.each do |type, msg| %>
<!--    TODO : Handle type with helper -->
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsMiam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">

    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <div class="container-fluid h-130">
      <h1 class="d-none">LetsMIAM</h1>
      <%= image_tag("logo.png", width: 400, class: "mx-auto d-block pt-5px") %>
    </div>
    <%= yield %>
  </body>
  <footer class="mt-auto">
    <%= render "layouts/footer" %>
  </footer>
</html>